apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jbXJ5ZXVpdWUwd28udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: c2FtaXIxMjM=
